services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: receitas_prod
    ports:
      - "3308:3306"
    volumes:
      - mysql_prod_data:/var/lib/mysql

  app:
    build: .
    restart: always
    env_file:
      - .env.prod
    ports:
      - "8002:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    command: >
      sh -c "
      composer install --no-interaction &&
      php artisan serve --host=0.0.0.0 --port=8000
      "

volumes:
  mysql_prod_data: