version: '3.8'

services:

  mysql_homolog:
    image: mysql:8
    container_name: mysql_homolog
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: receitas_homolog
    ports:
      - "3307:3306"
    volumes:
      - db_homolog:/var/lib/mysql

  mysql_prod:
    image: mysql:8
    container_name: mysql_prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: receitas_prod
    ports:
      - "3308:3306"
    volumes:
      - db_prod:/var/lib/mysql

  homolog:
    build: .
    container_name: app_homolog
    ports:
      - "8001:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql_homolog
    environment:
      DB_HOST: mysql_homolog
      DB_DATABASE: receitas_homolog
      DB_USERNAME: root
      DB_PASSWORD: root
      APP_ENV: local
      APP_DEBUG: true

  prod:
    build: .
    container_name: app_prod
    ports:
      - "8002:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql_prod
    environment:
      DB_HOST: mysql_prod
      DB_DATABASE: receitas_prod
      DB_USERNAME: root
      DB_PASSWORD: root
      APP_ENV: production
      APP_DEBUG: false

volumes:
  db_homolog:
  db_prod: