services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: receitas_prod
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    env_file:
      - .env.prod
    ports:
      - "8002:8000"
    depends_on:
      - mysql

volumes:
  mysql_data: