name: Deploy Produção

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

      - name: Deploy na VM
        run: |
          cd /opt/receitas-ci-cd/prod
          git fetch origin
          git reset --hard origin/main

          sudo docker compose down
          sudo docker compose up -d --build

      - name: Rodar migrations
        run: |
          sudo docker exec app_prod php artisan migrate --force

      - name: Cache Laravel
        run: |
          sudo docker exec app_prod php artisan config:cache
          sudo docker exec app_prod php artisan route:cache
          sudo docker exec app_prod php artisan view:cache