name: Deploy Produção

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

      - name: Deploy Produção
        run: |
          cd /opt/receitas-ci-cd/prod

          git fetch origin
          git reset --hard origin/main

          sudo docker compose -f docker-compose.prod.yml up -d --build

      - name: Aguardar MySQL
        run: |
          echo "Aguardando MySQL..."

          until sudo docker exec prod-mysql-1 mysqladmin ping -h localhost -uroot -proot --silent; do
            sleep 2
          done

          echo "MySQL pronto"

      - name: Rodar migrations
        run: |
          sudo docker exec prod-app-1 php artisan migrate --force

      - name: Seed (opcional)
        run: |
          sudo docker exec prod-app-1 php artisan db:seed --force || true

      - name: Cache Laravel
        run: |
          sudo docker exec prod-app-1 php artisan config:cache
          sudo docker exec prod-app-1 php artisan route:cache
          sudo docker exec prod-app-1 php artisan view:cache